name: Docker Basic CI

on:
  push:
    branches: [main]

jobs:
  test-image:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Build image
        run: docker build -t grafenoih:test .

      - name: Run container
        run: |
          docker run -d --name app -p 8000:8000 grafenoih:test
          echo "Container started"

      - name: Wait and test /health endpoint
        run: |
          for i in {1..12}; do
            if curl -fsS http://127.0.0.1:8000/health >/dev/null 2>&1; then
              echo "Application responding (health ok)"
              exit 0
            fi
            echo "Waiting (${i})..."
            sleep 5
          done
          echo "Failure: /health service did not respond"
          exit 1

      - name: Show logs if failed
        if: failure()
        run: docker logs app || true

      - name: Stop container
        if: always()
        run: docker rm -f app || true
